
---
title: "Project Guidelines"
author: "Rebecca C. Steorts, STA 490/690"
output: 
     pdf_document:
      includes: 
          in_header: custom2.tex
font-size: 8px
---

The goal of your project must be motivated by a real application of entity resolution. Students can work in groups no larger than groups of four. 

Deadlines:

- Friday, April 2: In class, run the general idea for approval by Professor Steorts
- Friday, April 9: First draft due of slides, paper, code
- Friday, April 16, Second draft due of slides, paper, code
- Wednesday, April 21, Final draft due of slides, paper
- Friday, April 23, Final presentations in class (10 minutes per group, including questions)

Each group will have the following goals:

1. Choose an application of entity resolution that is approved by Professor Steorts. What is the application and what are the goals of the applied problem that the group is going to tackle? 
2. Put forth a proposal motivated by their application to entity resolution that will help solve their applied problem. Be specific. 
3. Who is in charge of each part of the proposed methodology, and how will you achieve these goals. Write out a timeline and your deliverables.

The first step of your project is making sure that your proposal is reasonable and approved by Professor Steorts and Olivier. Please write up a short description, where we will provide feedback. 

Once your project is approved, your next steps are as follows:

1. Write an outline for your project that will turn into a report that will be no longer than 8 pages in length. 
2. You should have code for your project that is reproducible and matches your objectives. 
3. You should have a short presentation that summarizes your goals, application, methodology, and findings. Your presentation should be no longer than 10 minutes long. (If you're presenting as a group, divide this up equally). 

Sections of your presentation/paper should be:

- Your project idea and its motivation; what were you interested in exploring? Be clear about your goals. 
- Introduce the real data set that you're using. Where did it come from? 
- The methods being used. Give a high level overview. We only need details if you're changing the approach due to something specific for your project. 
- Your results; don’t show us every single result. That’s what the report is for. Give us
an overview of the general results and then pick some interesting results to discuss.
- Critical evaluation of the work; what else would you have done? Is there anything else you wish you would have done/had? What worked, what didn’t; what would you do next or tell someone to do next?
- Acknowledgements: resources, references, etc. 



