
---
title: "Quiz 1"
author: "Due March 19, 2021 at 5 PM EDT"
output: 
     pdf_document:
      includes: 
          in_header: custom2.tex
font-size: 8px
---

***General instructions for quiz***: Your code must be completely reproducible and must compile. No late homeworks will be accepted.

***Advice***: Start early on the quizzes early and it is advised that you not wait until the day of as these are meant to be longer and worked on within a group environment.

***Commenting code***
Code should be commented. See the Google style guide for questions regarding commenting or how to write code \url{https://google.github.io/styleguide/Rguide.xml}.

# Problem statement

Create a homework for the class that is broken up into five tasks, and provide a worked through solution and grading rubric to your homework. Make sure that goals for your homework assignment are clear, motivated by real data, and that you give helpful hints if needed. You can work in group sizes of no more than two students, and please choose a group leader.

\textbf{This group assignment will be graded based upon your five tasks, your grading rubric, and the correctness of your worked through solution.}

\textbf{Tip 1}: Use your teammates to walk through this exercise and make it a homework that is enjoyable, creative, and show cases what you think is most important about record linkage. 

\textbf{Tip 2}: Make sure that your write a complete solution to your homework exercise to make sure that it's doable and an appropriate level for the class. 

\textbf{Tip 3}: Creating this homework is an open note exercise. Oliver and Professor Steorts are here to help you if you get stuck on this assignment. The goal of this particular assignment to promote learning, interaction within your group, and a fun activity! 



